### ISSUE TITLE
Server cannot connect. Stops scanning.

### ISSUE THREAD

**Issue by colecarn** [rolandoislas/drc-sim#25]
I had a previous problem installing an older build, which you helped resolve. Now I'm having an issue where DRC Sim Server 1.4 won't connect. Same problem occurs if I try 1.5beta, and 1.5.

The server pairs fine with my Wii U. But when I go to connect, it starts scanning, then just stops and lists disconnected.

I ran a log, and I posted just the sections where "error" was reported. If you want the full log, let me know and I'll post a file.

Any help is appreciated, thank you.

```
2017-05-06 12:24:50,217 DEBUG:gui User clicked start server button
2017-05-06 12:24:50,217 DEBUG:gui Start server called
2017-05-06 12:24:50,218 DEBUG:drcsim Interface "wlx9cefd5ff7bb4" is unmanaged by network manager.
2017-05-06 12:24:50,218 DEBUG:gui Starting wpa supplicant
2017-05-06 12:24:50,220 DEBUG:wpa Connect called
2017-05-06 12:24:50,220 EXTRA:drcsim Attempting to execute command ['rfkill', 'unblock', 'wlan']
2017-05-06 12:24:50,224 VERBOSE:drcsim Command "['rfkill', 'unblock', 'wlan']" output 
2017-05-06 12:24:50,224 EXTRA:drcsim Attempting to execute command ['killall', 'wpa_supplicant_drc']
2017-05-06 12:24:50,233 EXTRA:drcsim Failed to execute command "['killall', 'wpa_supplicant_drc']" and got output "wpa_supplicant_drc: no process found"
2017-05-06 12:24:50,233 VERBOSE:drcsim Command "['killall', 'wpa_supplicant_drc']" output wpa_supplicant_drc: no process found

2017-05-06 12:24:50,234 DEBUG:wpa Starting wpa supplicant
2017-05-06 12:24:50,238 DEBUG:wpa Started wpa supplicant
2017-05-06 12:24:50,238 DEBUG:wpa Starting status check thread
2017-05-06 12:24:50,243 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:50,243 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:50,248 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:50,248 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:50,248 FINER:wpa Scan Results: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:50,248 FINER:wpa Status: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:50,249 FINER:wpa 30 seconds until start timeout
2017-05-06 12:24:51,256 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:51,256 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:51,261 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:51,261 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:51,261 FINER:wpa Scan Results: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:51,262 FINER:wpa Status: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:51,262 FINER:wpa 29 seconds until start timeout
2017-05-06 12:24:52,269 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:52,269 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:52,273 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:52,274 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:52,274 FINER:wpa Scan Results: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:52,274 FINER:wpa Status: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:52,274 FINER:wpa 28 seconds until start timeout
2017-05-06 12:24:53,281 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:53,281 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:53,286 EXTRA:drcsim Failed to execute command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" and got output "Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory"
2017-05-06 12:24:53,286 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" output Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:53,286 FINER:wpa Scan Results: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

2017-05-06 12:24:53,286 FINER:wpa Status: Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
```

```
2017-05-06 12:26:58,365 DEBUG:gui Wpa changed status to DISCONNECTED
2017-05-06 12:26:58,366 DEBUG:gui Stop server called
2017-05-06 12:26:58,366 DEBUG:wpa Stopping wpa status check
2017-05-06 12:26:58,366 EXTRA:wpa cannot join current thread
Traceback (most recent call last):
  File "/opt/drc_sim/venv_drc/local/lib/python2.7/site-packages/drcsim-1.4-py2.7.egg/src/server/util/wpa_supplicant.py", line 121, in stop
    self.status_check_thread.join()
  File "/usr/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
2017-05-06 12:26:58,370 DEBUG:wpa Stopping wpa process
2017-05-06 12:26:58,370 EXTRA:drcsim Attempting to execute command ['killall', 'wpa_supplicant_drc']
2017-05-06 12:26:58,379 VERBOSE:drcsim Command "['killall', 'wpa_supplicant_drc']" output 
2017-05-06 12:26:58,379 DEBUG:wpa Wpa stopped
2017-05-06 12:26:58,380 DEBUG:gui FrameRunServer activated
2017-05-06 12:26:58,380 EXTRA:drcsim Attempting to execute command ['iwlist', 'lo', 'frequency']
2017-05-06 12:26:58,385 VERBOSE:drcsim Command "['iwlist', 'lo', 'frequency']" output lo        no frequency information.
```

**Comment by rolandoislas** [comment]
I will need to see [wpa_supplicant_drc.log](https://github.com/rolandoislas/drc-sim/wiki/Logging).

**Comment by colecarn** [comment]
> Successfully initialized wpa_supplicant
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: SME: Trying to authenticate with 9c:e6:35:87:3b:9c (SSID='WiiU9ce635873b9c' freq=5765 MHz)
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: Failed to initiate AP scan
> wlx9cefd5ff7bb4: SME: Trying to authenticate with 9c:e6:35:87:3b:9c (SSID='WiiU9ce635873b9c' freq=5765 MHz)
> wlx9cefd5ff7bb4: CTRL-EVENT-TERMINATING

**Comment by rolandoislas** [comment]
This is a bug with the way unmanaged devices are added to the NetworkManager configuration by DRC Sim Server.

It currently adds one device per line which causes Network Manager issues with parsing:
```
[keyfile]
unmanaged-devices=mac:00:0a:00:0a:0a:00
[keyfile]
unmanaged-devices=mac:00:0b:00:0b:0b:00
```

Unmanaged entries should be in the following format:
```
[keyfile]
unmanaged-devices=mac:00:0a:00:0a:0a:00;mac:00:0b:00:0b:0b:00
```

Applying this change to `/etc/NetworkManager/NetworkManager.conf` manually will restore functionality.

**Comment by colecarn** [comment]
FYI my specs. Thought I'd list them in case this problem is specific to my setup.

DRC Sim installed on a Ubuntu 16.04.2 LTS VM Ware virtual machine
VM Network set to bridged
WiFi Adapter Panda N600 Dual Band Ralink chipset
Currently trying to get build 1.4 working, though problem occurs on 15. and 1.5beta as well.

Just as a recap. I was connecting perfectly fine a couple of weeks ago. I believe I had either the 1.4 or 1.5 beta build installed, which was installed using the easy method of the install script.

A few days ago, I created a new VM, and had issues staying connected, which I believe was on the latest 1.5 build. Then you helped resolve a problem installing the a 1.4 build using the new script you provided me.

I was able to connect a few times, but now I can't connect at all, even after fresh install.

I looked at the Network Manager, and it only shows one MAC address, even after a successful pairing. I listed it's contents below, though I changed part of the MAC address for security purposes.

Is my problem related to the errors that are appearing in the log I listed above? 

I also listed the last part of my log where DRC Sim disconnects.

```
[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq

[ifupdown]
managed=false
[keyfile]
unmanaged-devices=mac:9c:ef:00:00:00:00
```
```
2017-05-08 06:57:59,898 FINER:wpa Status: Selected interface 'wlx9cefd5ff7bb4'
wpa_state=AUTHENTICATING
address=9c:ef:dxxxxxxx

2017-05-08 06:57:59,898 DEBUG:gui Wpa changed status to CONNECTING
2017-05-08 06:58:00,905 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'status']" output Selected interface 'wlx9cefd5ff7bb4'
wpa_state=DISCONNECTED
address=9c:ef:dxxxxxxxx

2017-05-08 06:58:00,910 VERBOSE:drcsim Command "['wpa_cli_drc', '-p', '/var/run/wpa_supplicant_drc', 'scan_results']" output Selected interface 'wlx9cefd5ff7bb4'
bssid / frequency / signal level / flags / ssid
18:1b:exxxxxx7	2462	-38	[WPA-PSK-CCMP][WPA2--][WPS][ESS]	S2JLL
9c:e6:35:xxxxxxxc	5765	-54	[WPA2-PSK-CCMP][ESS]	\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
62:45:bxxxxxxxb	5745	-60	[WEP][ESS]	
9c:e6:3xxxxx5765	-52	[WPA2-PSK-CCMP][ESS]	WiiU9cexxxxxxxx
fa:8f:ca:xxxxxxx    2462	-60	[ESS]	

2017-05-08 06:58:00,910 FINER:wpa Scan Results: Selected interface 'wlx9cefd5ff7bb4'
bssid / frequency / signal level / flags / ssid
18:1b:ebxxxxxx2462	-38	[WPA-PSK-CCMP][WPA2--][WPS][ESS]	S2JLL
9c:e6:3xxxxxx	5765	-54	[WPA2-PSK-CCMP][ESS]	\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
62:45:bxxxxxx	5745	-60	[WEP][ESS]	
9c:e6:35:xxxxxx  5765	-52	[WPA2-PSK-CCMP][ESS]	WiiU9cxxxxxxxxx
fa:8f:ca:xxxxxxx	2462	-60	[ESS]	

2017-05-08 06:58:00,910 FINER:wpa Status: Selected interface 'wlx9cefd5ff7bb4'
wpa_state=DISCONNECTED
address=9c:ef:dxxxxxxxx

2017-05-08 06:58:00,910 DEBUG:gui Wpa changed status to DISCONNECTED
2017-05-08 06:58:00,911 DEBUG:gui Stop server called
2017-05-08 06:58:00,911 DEBUG:wpa Stopping wpa status check
2017-05-08 06:58:00,911 EXTRA:wpa cannot join current thread
Traceback (most recent call last):
  File "/opt/drc_sim/venv_drc/local/lib/python2.7/site-packages/drcsim-1.4-py2.7.egg/src/server/util/wpa_supplicant.py", line 121, in stop
    self.status_check_thread.join()
  File "/usr/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
2017-05-08 06:58:00,912 DEBUG:wpa Stopping wpa process
2017-05-08 06:58:00,912 EXTRA:drcsim Attempting to execute command ['killall', 'wpa_supplicant_drc']
2017-05-08 06:58:00,922 VERBOSE:drcsim Command "['killall', 'wpa_supplicant_drc']" output 
2017-05-08 06:58:00,922 DEBUG:wpa Wpa stopped
2017-05-08 06:58:00,922 DEBUG:gui FrameRunServer activated
2017-05-08 06:58:00,923 EXTRA:drcsim Attempting to execute command ['iwlist', 'lo', 'frequency']
2017-05-08 06:58:00,927 VERBOSE:drcsim Command "['iwlist', 'lo', 'frequency']" output lo        no frequency information.


2017-05-08 06:58:00,928 EXTRA:drcsim Attempting to execute command ['iwlist', 'ens33', 'frequency']
2017-05-08 06:58:00,933 VERBOSE:drcsim Command "['iwlist', 'ens33', 'frequency']" output ens33     no frequency information.


2017-05-08 06:58:00,934 EXTRA:drcsim Attempting to execute command ['iwlist', 'wlx9cefd5ff7bb4', 'frequency']
2017-05-08 06:58:00,938 VERBOSE:drcsim Command "['iwlist', 'wlx9cefd5ff7bb4', 'frequency']" output wlx9cefd5ff7bb4  32 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Channel 14 : 2.484 GHz
          Channel 36 : 5.18 GHz
          Channel 38 : 5.19 GHz
          Channel 40 : 5.2 GHz
          Channel 42 : 5.21 GHz
          Channel 44 : 5.22 GHz
          Channel 46 : 5.23 GHz
          Channel 48 : 5.24 GHz
          Channel 52 : 5.26 GHz
          Channel 54 : 5.27 GHz
          Channel 56 : 5.28 GHz
          Channel 58 : 5.29 GHz
          Channel 60 : 5.3 GHz
          Channel 62 : 5.31 GHz
          Channel 64 : 5.32 GHz
          Channel 100 : 5.5 GHz
          Channel 102 : 5.51 GHz
          Channel 104 : 5.52 GHz
          Channel 106 : 5.53 GHz
```

**Comment by rolandoislas** [comment]
The joining thread error is unrelated.

Make sure Network Manager lists the device as unmanaged in the GUI (or nmcli) and/or try stopping the service completely.

Is there something else that could be interfering with the device?

**Comment by colecarn** [comment]
It's connecting again on version 1.4. I did several reboots of my pc and wii u, as well as try different ports for my wifi adapter, and clean builds of Ubuntu. I have no idea what the issue was or is, but all of a sudden after another clean Ubuntu install, it started working again. Possibly a conflict between guest and host on the virtualization side with the wifi adapter. What confused me on the issue, is how it would successfully pair, but not connect. I hope the problem doesn't surface again.
