### ISSUE TITLE
install.sh error

### ISSUE THREAD

**Issue by CatotheCat11** [rolandoislas/drc-sim#72]
The install.sh file keeps failing to install the drc-sim server properly. Below is the file output. I've also tried the develop version, it doesn't work either.

Drc-sim installer (script version 1.1.3)
	https://github.com/rolandoislas/drc-sim
Command apt-get found.
Installing dependencies.
python3 [INSTALLED]
python3-pip [INSTALLED]
net-tools [INSTALLED]
wireless-tools [INSTALLED]
sysvinit-utils [INSTALLED]
psmisc [INSTALLED]
rfkill [INSTALLED]
isc-dhcp-client [INSTALLED]
ifmetric [INSTALLED]
python3-tk [INSTALLED]
gksu [INSTALLED]
git [INSTALLED]
libssl-dev [INSTALLED]
libnl-genl-3-dev [INSTALLED]
gcc [INSTALLED]
make [INSTALLED]
pkg-config [INSTALLED]
libavcodec-dev [INSTALLED]
libswscale-dev [INSTALLED]
libjpeg-dev [INSTALLED]
cmake [INSTALLED]
Found existing git directory /opt/drc_sim/wpa
Stashed git changes
Updating git repo
Updated git repo
Compiling wpa_supplicant_drc
Compile log at /opt/drc_sim/wpa/wpa_supplicant/make.log
Installing wpa_supplicant_drc and wpa_cli_drc to /usr/local/bin
Compiled wpa_supplicant
Found existing git directory /opt/drc_sim/drc_sim_c
Stashed git changes
Updating git repo
Updated git repo
Compiling drc_sim_c
Compile log at /opt/drc_sim/drc_sim_c/make.log
Installing drc_sim_c to /usr/local/bin
Compiled drc_sim_c
Installing DRC Sim Server GUI/CLI Utility
Found existing git directory /opt/drc_sim/drc
Stashed git changes
Updating git repo
Updated git repo
Installing setuptools
Attempting to remove previous installations
Using branch "develop" for drc-sim install
Installing drc-sim
Downloading Python packages. This may take a while.
running install
running bdist_egg
running egg_info
writing drcsim.egg-info/PKG-INFO
writing dependency_links to drcsim.egg-info/dependency_links.txt
writing requirements to drcsim.egg-info/requires.txt
writing top-level names to drcsim.egg-info/top_level.txt
reading manifest file 'drcsim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'drcsim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/drc-sim-backend to 755
copying drcsim.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/opt/drc_sim/drc/setup.py", line 18, in <module>
    setup(name='drcsim',
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/bdist_egg.py", line 222, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/bdist_egg.py", line 275, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/bdist_egg.py", line 391, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/bdist_egg.py", line 430, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
Failed to install drc-sim

**Comment by FOSSHipster** [comment]
How did you solve this issue?

**Comment by Millymilo00** [comment]
Having this issue too, how'd you fix it?

**Comment by CatotheCat11** [comment]
Sorry, but it was 2 years ago, I completely forgot how I fixed it...

**Comment by Millymilo00** [comment]
Sorry if it gave a random notification for something this old, thankfully I ended up finding a workaround,

The install.sh file is _supposed_ to download the netifaces, pexpect, and distro python libraries, but fails to for whatever reason. So all I had to do is download them using pip3, after doing that I ran the install.sh again and it worked.
