### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by OniLink** [rolandoislas/drc-sim#73]
As of python 3.8, the following error occurs when trying to run the server after installing via the python script:

Traceback (most recent call last):
  File "/usr/bin/drc-sim-backend", line 4, in <module>
    __import__('pkg_resources').run_script('drcsim==2.0', 'drc-sim-backend')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/EGG-INFO/scripts/drc-sim-backend", line 8, in <module>
    from src.server.ui.cli.cli_main import CliMain
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/src/server/ui/cli/cli_main.py", line 6, in <module>
    from src.server.data.resource import Resource
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/src/server/data/resource.py", line 6, in <module>
    from src.server.util.logging.logger import Logger
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/src/server/util/logging/logger.py", line 6, in <module>
    from src.server.util.os_util import OsUtil
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/src/server/util/os_util.py", line 5, in <module>
    class OsUtil:
  File "/usr/lib/python3.8/site-packages/drcsim-2.0-py3.8.egg/src/server/util/os_util.py", line 9, in OsUtil
    distro = _platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by Veemyu** [comment]
Thanks for letting me know, and opening an Issue. I'll try to replicate this Issue ASAP.

**Comment by Veemyu** [comment]
Couldn’t replicate this issue on Arch Linux.
Can you tell me your OS?

**Comment by OniLink** [comment]
I am also using Arch Linux

**Comment by Veemyu** [comment]
Try drc-sim-e from My Repo it’s an enhanced version of DRC sim optimised for more modern Distros.

**Comment by OniLink** [comment]
That installs, thank you!
