### ISSUE TITLE
module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by M3KAI5ER44** [rolandoislas/drc-sim#77]
I am lost, I have been trying to get this to work for the past 6 hours and i can't get it to run at all. the output when I try to run is: `Traceback (most recent call last):
  File "/usr/local/bin/drc-sim-backend", line 4, in <module>
    __import__('pkg_resources').run_script('drcsim==2.0', 'drc-sim-backend')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/EGG-INFO/scripts/drc-sim-backend", line 8, in <module>
    from src.server.ui.cli.cli_main import CliMain
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/src/server/ui/cli/cli_main.py", line 6, in <module>
    from src.server.data.resource import Resource
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/src/server/data/resource.py", line 6, in <module>
    from src.server.util.logging.logger import Logger
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/src/server/util/logging/logger.py", line 6, in <module>
    from src.server.util.os_util import OsUtil
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/src/server/util/os_util.py", line 5, in <module>
    class OsUtil:
  File "/usr/local/lib/python3.8/dist-packages/drcsim-2.0-py3.8.egg/src/server/util/os_util.py", line 9, in OsUtil
    distro = _platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'` HELP!

**Comment by M3KAI5ER44** [comment]
i found a closed issue and will read it, i will reopen if needed.

**Comment by M3KAI5ER44** [comment]
The closed issue did not help enough so I will reopen for now.

**Comment by M3KAI5ER44** [comment]
i finally figured it out

**Comment by vassdeniss** [comment]
Next time write the solution?
