### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by vassdeniss** [rolandoislas/drc-sim#84]
I'm getting this error when trying to launch on Debian 11
`Traceback (most recent call last):
  File "/usr/local/bin/drc-sim-backend", line 4, in <module>
    __import__('pkg_resources').run_script('drcsim==2.0', 'drc-sim-backend')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/EGG-INFO/scripts/drc-sim-backend", line 8, in <module>
    from src.server.ui.cli.cli_main import CliMain
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/src/server/ui/cli/cli_main.py", line 6, in <module>
    from src.server.data.resource import Resource
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/src/server/data/resource.py", line 6, in <module>
    from src.server.util.logging.logger import Logger
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/src/server/util/logging/logger.py", line 6, in <module>
    from src.server.util.os_util import OsUtil
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/src/server/util/os_util.py", line 5, in <module>
    class OsUtil:
  File "/usr/local/lib/python3.9/dist-packages/drcsim-2.0-py3.9.egg/src/server/util/os_util.py", line 9, in OsUtil
    distro = _platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'`

**Comment by Veemyu** [comment]
Please use https://github.com/alinach120602/drc-sim-e/wiki/Install
